// Script de migração ÚNICO (issue #26) — roda 1x pra popular a tabela
// `fluxos_planejados` (shared/fluxosPlanejadosDb.ts) a partir dos 74
// registros que antes viviam hardcoded em src/fluxos/catalogo.ts (removido
// depois desta migração, PR #24 tinha a origem desses dados: 71 de
// GET /integra/assunto/categorias + 3 achadas só na planilha de
// palavras-chave). Uso: npm run seed:fluxos-planejados (precisa
// DATABASE_URL no ambiente/.env).
import "dotenv/config";
import pg from "pg";
import { fluxosPorId } from "../src/fluxos/index.js";

const { Pool } = pg;

interface FluxoPlanejado {
  id: string;
  nome: string;
  descricao: string;
  idCategoriaAssuntoVerde: number;
  palavrasChave: string[];
  // Issue #22 — redirecionamento permanente (não "em construção").
  mensagemFixa?: string;
}

const DADOS_SEED: FluxoPlanejado[] = [
  { id: "89209462-6276-42c9-9c06-62628783dc6d", nome: "pensão alimentícia", descricao: "Atendimento sobre pensão alimentícia", idCategoriaAssuntoVerde: 10016, palavrasChave: ["pensão", "alimentícia", "exoneração", "revisão", "modificação", "regularização", "fgts", "grávida", "grávidicos", "idoso", "pai", "mãe", "alimentos", "execução", "parar de pagar", "mudar o valor", "entrar com pedido de pensão", "pedir pensão para o filho", "cobrar pensão atrasada", "pedir pensão grávida", "aumentar o valor da pensão", "tirar a pensão", "ele não paga a pensão", "acordo de boca sobre pensão", "penção", "alimento pro filho", "valor de pemsão", "execusão de alimentos", "processar o pai da criança", "o pai não ajuda o filho", "ele não ajuda com a criança", "não recebo nada para meu filho", "não recebo ajuda para meu filho", "o pai não ajuda nas despesas", "ele não ajuda com o filho", "abrir processo de pensão"] },
  { id: "c1b3f113-5b2e-45e2-9ca9-ac5ba30bc1fd", nome: "falecimento na família", descricao: "Atendimento para herança, inventário e bens de parentes que faleceram", idCategoriaAssuntoVerde: 10017, palavrasChave: ["alvará", "inventário", "herança", "cremação", "exumação", "partilha de bens", "sepultamento", "enterro", "óbito", "fgts", "testamento", "terreno", "pis", "morte", "certidão de inexistência de dependentes", "cemitério", "enterrar", "sepultar", "retirada restos mortais", "sepultura", "desenterrar", "transcrição", "registro", "sucessão", "herdeiros", "espólio", "certidão", "faleceu", "morreu", "falecido", "deixou", "falescimento", "heransa", "pessoa falecida", "perdi um familiar", "morte na família"] },
  { id: "180001d2-5e0c-4f27-aa13-f425149a1336", nome: "educação, creche, escola", descricao: "Atendimento para vaga, matrícula, cobranças ou problemas com educação", idCategoriaAssuntoVerde: 10019, palavrasChave: ["colégio", "creche", "particular", "pública", "ensino médio", "fundamental", "mensalidade", "dívida", "matrícula", "transferência", "vaga", "mediador", "vestibular", "universidade", "indenização", "cobrança", "direito à educação", "pré-escola", "rematrícula", "fies", "prouni", "histórico escolar", "diploma", "distância da escola", "aluno com deficiência", "transporte escolar", "ensino", "escola", "faculdade", "educação"] },
  { id: "6842b257-ee0b-48e8-8b1f-d13092a6045f", nome: "busca e apreensão", descricao: "Atendimento para busca e apreensão de coisas e pessoas", idCategoriaAssuntoVerde: 10020, palavrasChave: ["menor", "arresto", "sequestro", "tirou o filho", "incapaz", "entrega", "documentos", "criança", "adolescente", "bem", "bens", "pessoa", "veículo", "carro", "moto", "objeto", "não devolveram a criança após a visita", "vão tomar meu carro", "vão pegar meu carro", "querem tomar meu veículo", "não devolveram meu filho", "não devolveram minha filha"] },
  { id: "e4e13ef2-6b38-4696-9e0a-51561b254a12", nome: "casamento e divórcio", descricao: "Orientações sobre casamento, divórcio e união estável", idCategoriaAssuntoVerde: 10021, palavrasChave: ["matrimônio", "celebração", "casar", "alteração de regime de bens", "pacto antenupcial", "amigado", "amigo", "companheira", "companheiro", "conversão", "convivência", "convivente", "dissolução", "juntado", "junto", "justificação", "condomínio", "divisão de bens", "inventário", "partilha de bens", "autorização", "suprimento judicial", "consentimento", "contrato pré-nupcial", "pensão por morte", "benefício previdenciário", "inss", "desfazer", "transcrição", "registro", "divórcio consensual", "divórcio litigioso", "divórcio extrajudicial", "conversão de união estável em casamento", "escritura de união estável", "separação", "regime de bens", "dissolução de união estável", "quero me separar", "como dar entrada no divórcio", "documento para união estável", "provar união estável", "habilitação para casamento", "casamento", "união estável", "divórcio", "me separei do meu marido", "me separei da minha esposa", "terminamos a relação"] },
  { id: "b23e8161-49f3-480c-935b-3bbefd05532a", nome: "imóvel", descricao: "Problemas com imóvel, aluguel, condomínio, posse ou direito à moradia", idCategoriaAssuntoVerde: 10022, palavrasChave: ["usucapião", "rgi", "compra venda", "hipoteca", "cancelamento", "levantamento", "retificação de registro", "anulação", "casa", "apartamento", "busca cartorária", "ônus reais", "terreno", "chaves", "cláusula abusiva", "consignação", "depósito", "despejo", "dono", "inquilino", "locador", "locatário", "locação", "móveis", "multa", "revisão", "revisional", "senhorio", "comodato", "empréstimo", "esbulho", "interdito probitório", "invasão", "manutenção", "ocupação", "ocupado", "pertubação", "posse", "reintegração", "reivindicação", "retomada", "animais", "área comum", "assembleia", "atraso", "barulho", "cachorro", "edificio", "síndico", "averbação", "obra", "construção", "condomínio", "prestação de contas", "desmembramento", "escritura", "promessa de compra e venda", "distrato imobiliário", "adjudicação compulsória", "atraso na entrega das chaves", "rachadura", "devolver", "áreas comuns", "proprietário", "uzucapião", "despejar", "contrato"] },
  { id: "34a3d5c5-c9c4-4d83-825e-9ca35f5d1fb8", nome: "direito de vizinhança", descricao: "Atendimento sobre conflitos entre vizinhos — barulho, divisas, uso do imóvel.", idCategoriaAssuntoVerde: 10024, palavrasChave: ["vizinho", "muro", "árvore", "barulho", "construção", "obra", "poda", "nova", "nunciação", "passagem", "serventia", "janela", "imóvel", "casa", "condomínio", "prédio", "direito de passagem forçada", "som alto", "festas", "infiltração", "janela virada para o meu quintal", "privacidade", "vizinhansa", "briga", "problema com vizinho", "conflito com vizinho", "direito entre vizinhos", "conflito de vizinhança"] },
  { id: "fe68a29d-e1e0-465c-a490-9e532e785c14", nome: "nascimento", descricao: "Dna, reconhecer pai ou mãe e problemas com certidão de nascimento", idCategoriaAssuntoVerde: 10028, palavrasChave: ["parto", "maternidade", "paternidade", "certidão", "registro", "transcrição", "translado", "declaração de nascido vivo", "tardio", "dna", "reconhecimento", "socioafetiva", "registrar", "pai", "nome", "meu filho nasceu", "minha filha nasceu", "nasceu meu bebê"] },
  { id: "63ece0e5-1f89-489d-9c21-27013a4cfbde", nome: "paternidade", descricao: "Investigação de paternidade, exame de dna e nome do pai na certidão", idCategoriaAssuntoVerde: 10029, palavrasChave: ["reconhecimento", "investigação", "maternidade", "pai", "mãe", "negatória", "preso", "criança", "adolescente", "herdeiros", "exame", "dna", "socioafetiva", "registrar", "meu", "minha", "tirar", "padrasto", "sobrenome", "filiação", "quero saber quem é o pai", "teste de dna"] },
  { id: "a8f33628-c84b-417b-879e-c55725240d8e", nome: "regulamentar visita", descricao: "Direito de visitas: crianças, adolescentes, idosos e pessoas presas", idCategoriaAssuntoVerde: 10030, palavrasChave: ["criança", "adolescente", "incapaz", "idoso", "preso", "visitante", "guardião", "busca e apreensão", "menor", "visitação", "convivência", "visita", "ver", "visitar", "direito de visita", "direito de visitação", "regular visitas", "visitas ao filho", "visita a filho", "quero ver meu filho", "quero ver minha filha", "combinar visitas", "definir dias de visita", "organizar visita ao filho", "horário de visita", "como ver meu filho"] },
  { id: "fc0224cb-20b6-4e80-bc56-f048eb67bb27", nome: "gratuidade documentos", descricao: "2ª via de documentos e correção de dados em certidões e registro civil", idCategoriaAssuntoVerde: 10038, palavrasChave: ["segunda via", "certidão", "identidade", "rg", "carteira de motorista", "cnh", "2ª via", "nome", "documento", "busca cartorária", "isenção de taxa", "ofício", "graça", "errado", "gratis", "gratuidade", "obtenção", "regularização de documentos pessoais", "documento pessoal", "tirar documento", "documento de graça"] },
  { id: "3792f3ba-4fbd-4334-9fd5-6a6dde351d83", nome: "detran", descricao: "Atendimento sobre questões relacionadas ao DETRAN — carteira de motorista, veículos, multas.", idCategoriaAssuntoVerde: 10040, palavrasChave: ["habilitação", "categoria", "prontuário", "renovação", "exames", "cnh", "multa", "tranferência", "titularidade", "veículo", "carro", "automóvel", "moto", "motocicleta", "permissão", "gratuidade", "depósito", "detro", "guarda municipal", "ipva", "polícia", "rebocado", "reboque", "cassação", "suspensão", "carteira de motorista", "carta", "infração", "penalidade", "certificado de registro de veículo (crv)", "certificado de registro e licenciamento do veículo (crlv)", "infrações", "pontos", "lei seca", "suspensa", "comprei um carro e o antigo dono não transferiu", "meu carro foi rebocado, como tirar do depósito", "carro sem documento", "cnh vensida"] },
  { id: "a246a56e-a4bb-454d-862a-663ad3622b28", nome: "imposto/taxa", descricao: "Impostos municipais ou estaduais: cobrança, dívidas e isenção.", idCategoriaAssuntoVerde: 10041, palavrasChave: ["iptu", "ipva", "iluminação pública", "incêndio", "itd", "itbi", "imposto de renda", "bombeiros", "isenção", "doação", "inventário", "veículo", "detran", "imóvel", "carro", "casa", "bens", "bem", "multa", "cemitério", "manutenção", "conservação", "sepultura", "ossário", "tributo", "pagamento", "lançamento", "dívida", "devendo", "contribuição", "contribuinte", "encargo", "parcelamento", "cobrança em devida", "duplicidade", "morte", "indevida", "taxas", "repetição de indébito", "bitributação", "valor", "imposto", "taxa"] },
  { id: "a029b11d-fd48-4ef7-a65b-26ebccc3a991", nome: "guarda", descricao: "Atendimento para regularizar a guarda de criança / adolescente", idCategoriaAssuntoVerde: 10042, palavrasChave: ["tirou o filho", "criança", "adolescente", "incapaz", "entrega", "menor", "sequestro", "poder", "alternada", "guarda compartilhada", "guarda unilateral", "guarda alternada", "alienação parental", "guarda de fato", "busca e apreensão de menor", "ver", "pega", "filho", "filha", "abandono afetivo"] },
  { id: "3e94e53d-15cb-43f5-9467-11f0bde4d40e", nome: "concurso público", descricao: "Orientações sobre concursos públicos", idCategoriaAssuntoVerde: 10043, palavrasChave: ["prova", "comlurb", "banco do brasil", "petrobrás", "eletrobrás", "edital", "isncrição", "vestibular", "convocação", "nomeação", "aprovação", "reprovação", "colocação", "furnas", "processo seletivo", "exame", "cadastro de reserva", "taf", "teste de aptidão física", "passei dentro das vagas e não me chamaram", "fui reprovado no exame psicotécnico", "quero entrar na justiça para anular uma questão", "o concurso venceu e não fui nomeado", "certame", "erro na prova", "recurso contra questão"] },
  { id: "ad2e1abf-2f97-4792-acc9-837be5ee0cc1", nome: "adoção", descricao: "orientações sobre adoção", idCategoriaAssuntoVerde: 10044, palavrasChave: ["incluir o nome", "padastro", "madastra", "unilateral", "fila", "relação socioafetiva", "habilitação", "criança", "cadastro nacional de adoção", "sistema nacional de adoção e acolhimento", "habilitação para adoção", "adoção unilateral", "adoção tardia", "quero adotar uma criança", "como entrar na fila de adoção", "adotar um bebê", "dar entrada na papelada para adotar", "entregar bebê para adoção", "doar o filho", "inscrever na fila", "regularizar guarda para adoção", "formalizar adoção", "assistência jurídica para adotar", "buscar certidão de adoção", "adosão", "adotar um menor", "fila do juizado para criança", "cadastro de adoção", "adotar criança", "adotar filho"] },
  { id: "60b16fa6-a265-42e2-b548-2ceea42e4fc5", nome: "erro médico", descricao: "Erro médico e falha no atendimento: pedidos de indenização e danos", idCategoriaAssuntoVerde: 10045, palavrasChave: ["indenização", "tratamento", "médicos", "responsabilidade civil", "negligência", "imprudência", "imperícia", "dano", "diagnóstico errado", "hospital", "falha médica", "o médico errou", "recebi tratamento errado", "fizeram procedimento errado", "medicação errada", "deram remédio errado", "erro em cirurgia"] },
  { id: "ec20bc4a-560e-4d4a-bd00-f80718c2c3eb", nome: "representar outra pessoa", descricao: "Orientações sobre como representar outra pessoa em processo ou atendimento.", idCategoriaAssuntoVerde: 10046, palavrasChave: ["representação", "anulação", "curador", "decisão apoiada", "deficiência mental", "faculdades mentais", "prova de vida", "representar", "revogação", "procuração", "demência", "movimentar", "acamado", "acamada", "interditar", "poderes", "tutela", "curatela", "interdição", "interdicao"] },
  { id: "2ce11bc8-2cfa-4690-8aa3-272f76e48877", nome: "aposentadoria", descricao: "Orientações sobre aposentadoria", idCategoriaAssuntoVerde: 10047, palavrasChave: ["auxílio doença", "auxílio acidente", "invalidez", "trabalho", "contribuição", "inss", "servidor público", "iperj", "rio previdência", "benefício", "concessão", "revisão", "empregado", "empregador", "salário", "tempo de contribuição", "aposentadoria rural", "dar entrada na aposentadoria", "pedir aposentadoria por doença", "revisão de aposentadoria", "aposentadoria com erro no valor", "encostar pelo inss", "me aposentar por idade", "já tenho idade para aposentar", "minha aposentadoria não sai", "apozenta", "aposenta", "tempo de serviço", "incapacidade", "direito a aposentadoria", "idade para aposentar", "parei de trabalhar por doença"] },
  { id: "b670024b-a9a2-4e98-8f16-f5d9ba5402bc", nome: "saúde", descricao: "Atendimento para acesso à rede de saúde pública ou particular", idCategoriaAssuntoVerde: 10049, palavrasChave: ["fralda", "prótese", "órteses", "leite especial", "exame", "remédio", "medicamento", "transferência", "internação", "uti", "cti", "cirurgia", "operação", "negativa", "plano de saúde", "cadeira de roda", "internação compulsória", "prontuário médico", "interrupção", "gravidez", "transporte", "aborto", "carência", "home care", "cobertura", "doença", "negou", "fila", "operar", "medicações", "direito à saúde", "acesso à saúde", "atendimento médico", "direito a saúde", "acesso a saúde", "tratamento de saúde", "assistência médica", "consulta", "cirugia pelo sus"] },
  { id: "c3ef627f-f4e5-4172-9887-a844e2dcec27", nome: "acidente de trabalho", descricao: "atendimento relacionado à acidente de trabalho", idCategoriaAssuntoVerde: 10050, palavrasChave: ["empregado", "empregador", "invalidez", "indenização", "trajeto", "percurso", "inss", "benefício", "revisão", "concessão", "doença", "salário", "auxílio acidente", "auxílio doença", "doença profissional", "doença do trabalho", "cat", "comunicação de acidente de trabalho", "me machuquei no serviço", "sofri um acidente na empresa", "me acidentei trabalhando", "caí no trabalho", "travei a coluna no serviço", "fiquei doente por causa do emprego", "empresa não quer emitir a cat", "me acidentei indo trabalhar", "ler", "dort", "burnout", "depressão por trabalho", "incapacidade para o trabalho", "reabilitação profissional", "processar a empresa por acidente", "indenização por acidente de trabalho", "pensão por invalidez", "receber seguro acidentário", "afastamento pelo inss por acidente", "acindente de trabalho", "machuquei na firma", "pegar auxilio acidente", "entrar na justiça contra empresa acidente", "me machuquei trabalhando", "me machuquei na empresa", "me machuquei no trabalho", "me feri trabalhando", "acidente de serviço", "me machuquei na obra"] },
  { id: "f995820a-8db3-46a1-b927-80bc746bb3bf", nome: "acidente de trânsito", descricao: "atendimento relacionado à acidente de trânsito", idCategoriaAssuntoVerde: 10052, palavrasChave: ["dpvat", "seguro", "indenização", "batida", "colisão", "conserto", "sinistro", "atropelamento", "boletim de ocorrência", "brat", "boletim de registro de acidente de trânsito", "bateram no meu carro", "eu bati no carro", "engavetamento", "motoqueiro me fechou", "caí de moto", "carro deu pt", "conserto do carro", "orçamento de oficina", "franquia do seguro", "indenização por batida", "dano moral por acidente", "lucros cessantes", "dar entrada no dpvat", "acindente de transito", "batida de veiculo", "procesar quem bateu no meu carro", "bateram no meu veiculo", "traseira", "lateral", "dianteira", "retrovisor", "atropelado"] },
  { id: "007e01e8-6c66-4c7a-9ce2-5be75e5a883c", nome: "abrigo", descricao: "atendimento para conseguir abrigo para pessoas em situação de risco", idCategoriaAssuntoVerde: 10053, palavrasChave: ["casa de repouso", "violência doméstica", "abandono", "idoso", "criança", "menor", "morador de rua", "adolescente", "proteção", "asilo", "refúgio", "maria da penha", "preciso de um lugar para dormir", "casa de passagem", "albergue", "abrigo municipal", "casa de acolhida", "centro de acolhimento", "lugar seguro para mulher", "orfanato", "vaga em abrigo", "retirar do abrigo", "abrico", "alberque", "aujuda pra morar", "onde morar de graça", "cassa de apoio", "sem teto", "lar", "mendigo", "acolhimento", "acolher idoso", "abrigamento", "pedido de abrigamento", "preciso de abrigo", "preciso de um lugar pra ficar", "preciso de um lugar seguro", "preciso de um lugar pra passar a noite", "não tenho onde ficar", "não tenho pra onde ir", "idoso abandonado", "idoso sem família", "onde posso ficar", "onde posso dormir", "tem abrigo pra mim", "tem abrigo na cidade", "tem lugar pra ficar", "abrigu", "albergi", "alberg", "abrigo para pessoas com alzheimer"] },
  { id: "ea760719-4a1d-47a2-9a63-f40f01b4d890", nome: "concessionárias", descricao: "Atendimento sobre problemas com concessionárias de serviços públicos (água, luz, gás).", idCategoriaAssuntoVerde: 10054, palavrasChave: ["consumidor", "ampla", "luz", "telefonia", "operadora", "cedae", "ceg", "água", "gás", "empresas de ônibus", "telefone", "spc", "serasa", "dano", "indenização", "oi", "claro", "tim", "vivo", "nextel", "prestadora", "supervia", "trem", "metrô", "comlurb", "corte", "interrupção", "rio luz", "fetranspor", "loja", "light", "energia", "cobrança", "ônibus", "empresa", "enel", "águas do rio"] },
  { id: "3e74ff06-c3f7-400d-957d-957021ea9572", nome: "pedidos de indenização", descricao: "Indenização por danos contra empresas, órgãos públicos ou pessoas", idCategoriaAssuntoVerde: 10055, palavrasChave: ["reparação", "empresa", "pessoa física", "órgão público", "estado", "município", "prefeitura", "morte em penitenciária", "responsabilidade cível", "dano material", "dano moral", "dano estético", "obrigação", "fazer", "não fazer", "dar", "rio águas", "processo administrativo", "licença", "trienio", "anulação negócio jurídico", "servidor público", "criança", "adolescente", "indenização", "responsabilidade civil", "danos morais", "danos materiais", "lucros cessantes", "reparação de danos", "pedir ressarcimento", "processo por perdas e danos", "quero processar por danos morais", "fui lesado", "tive um prejuízo", "quero meu dinheiro de volta", "fui enganado por uma empresa", "fui humilhado", "nome no spc/serasa indevido", "cobrança indevida", "negativação indevida", "problema com voo / companhia aérea", "agressão ou injúria", "cobrar", "reaver valor", "limpar nome", "indenisatoria", "indenisacao", "processo de indenização", "ação indenizatória", "pedido de indenização", "pedir indenização", "pedir danos morais", "pedir danos materiais", "reparação por danos", "fui prejudicado", "tive prejuízo", "me lesaram", "cancelaram meu voo", "bagagem extraviada", "comprei e não recebi", "paguei e não recebi", "serviço mal prestado", "nome no serasa", "nome no spc", "sujaram meu nome", "meu nome foi negativado", "negativaram meu nome", "posso processar", "tenho direito a indenização", "quero meus direitos", "quero ser ressarcido", "agressão policial", "invasão de domicílio", "violência", "pm", "direitos dos agentes de segurança", "violação de direitos fundamentais"] },
  { id: "6e62a537-8da2-48a5-8d61-e9ed9082e65a", nome: "aluguel social", descricao: "Orientações sobre o benefício aluguel social", idCategoriaAssuntoVerde: 10056, palavrasChave: ["benefício", "estado", "município", "prefeitura", "moradia", "subsídio", "popular", "programa", "auxílio", "benefício de auxílio-moradia", "cadúnico", "defesa civil", "minha casa caiu", "desmoronamento", "desabamento", "enchente", "inundação", "área de risco", "minha casa foi interditada", "remoção", "ajuda do governo para pagar aluguel", "dinheiro para moradia", "auxílio para quem perdeu a casa", "cadastro para ganhar o aluguel", "não tenho onde morar", "bolsa aluguel", "como receber o aluguel social", "inscrição no aluguel social", "aluguel social atrasado", "consultar pagamento do auxílio", "documentos para aluguel social", "aluguel socila", "auxilio moradia governo", "receber aluguel da prefeitura", "ajuda de custo pra aluguel", "auxílio aluguel", "benefício de aluguel"] },
  { id: "31cb99fc-6047-481d-9c0b-e0d6faae2fcb", nome: "empresas e mei", descricao: "Atendimento para empresas sem condições de pagar advogados e custas", idCategoriaAssuntoVerde: 10057, palavrasChave: ["constituição", "abertura", "ong", "oscips", "organizações religiosas", "fundação", "fins lucrativos", "sociedade", "empresa", "capital", "alteração", "ata", "diretoria", "registro", "gratuidade", "sócio", "exlusão", "retirar", "tirar", "falência", "recuperação judicial", "contrato social", "atos constitutivos", "pj", "terreiro", "candomblé", "umbanda", "religião", "afro", "regularizar", "regularização", "pessoa jurídica", "cnpj", "mei", "estatuto", "pêssoa juridica", "atendimento pra firma", "empreza"] },
  { id: "ea9c1a50-3346-4b42-aa87-a7024fdd3267", nome: "auxílio reclusão", descricao: "Orientações sobre o benefício auxílio reclusão", idCategoriaAssuntoVerde: 10058, palavrasChave: ["benefício", "pensão", "preso", "detento", "auxílio-reclusão", "meu marido está puxando pena, como recebo o auxílio?", "pedir auxílio-reclusão", "dar entrada no benefício de preso", "auxilio presidiário", "benefício para família de preso", "benefício para dependentes do preso", "meu marido foi preso e preciso de benefício", "o pai dos meus filhos foi preso"] },
  { id: "9985afbb-e784-41cc-838e-ab402091562c", nome: "bancos e financeiras", descricao: "Bancos, financeiras, seguradora: cobranças, dívidas, juros, indenização", idCategoriaAssuntoVerde: 10059, palavrasChave: ["juros", "conta", "fatura", "renegociação", "dívidas", "negociação", "parcelamento", "spc", "serasa", "leasing", "financiamento", "cartão de crédito", "extrato", "bloqueio", "cheque especial", "lis", "financeira", "cobrança", "cláusula abusiva", "plano econômico", "plano verão", "plano collor", "plano bresser", "reajuste de contrato", "seguro", "pis", "pasep", "empréstimo", "fraude", "golpe", "salário", "renda", "superendividamento", "juros abusivos", "empréstimo consignado", "contrato bancário", "compra não reconhecida", "nome no spc/serasa", "fizeram um empréstimo no meu nome", "o juros está muito alto", "enprestimo", "juros de banco", "seraza", "problema com banco", "problema com financeira", "dívida com banco", "dívida com financeira", "contrato com banco", "serviço bancário", "empréstimo no banco", "empréstimo no meu nome", "emprestimu"] },
  { id: "7e3bbc4b-2371-4155-9e4b-82ea05ed0293", nome: "cobrança", descricao: "Atendimento para cobrança de dívidas ou entrega de coisas", idCategoriaAssuntoVerde: 10060, palavrasChave: ["contrato", "prazo", "pagamento", "débito", "duplicata", "nota promissória", "credor", "crédito", "dívida", "entrega", "indevida", "cobrança de dívida", "cobrança de valor", "cobrar dinheiro", "cobransa"] },
  { id: "24d83bd8-325c-4eb9-be9d-68d554c22831", nome: "citação/intimação", descricao: "Orientações sobre o recebimento de citações e intimações", idCategoriaAssuntoVerde: 10062, palavrasChave: ["mandado", "audiência", "prazo", "resposta", "precatória", "rogatória", "correios", "postal", "oficial de justiça", "eletrônica", "execução", "penhora", "notificação", "chegou um papel da justiça", "chegou uma carta do fórum", "o oficial de justiça foi na minha casa", "recebi uma carta do juiz", "me intimaram para audiência", "intimasao", "citasao"] },
  { id: "6fffc351-ad03-456d-b3c0-c8bb5d9e653f", nome: "relação de consumo", descricao: "Atendimento relacionado à defesa do consumidor", idCategoriaAssuntoVerde: 10063, palavrasChave: ["consumidor", "venda casada", "produto", "defeito", "indenização", "dano", "reparação", "moral", "material", "estético", "cobrança", "juros", "renegociação", "dívida", "cláusula abusiva", "reajuste de contrato", "anulação negócio jurídico", "empréstimo", "aparelho", "vício", "serviço", "arrependimento", "atraso", "entrega", "produto com defeito", "negativação", "passagens aéreas", "cancelamento", "comprei", "internet", "garantia", "direito do consumidor", "problema com empresa", "problema com compra", "problema com produto", "problema com serviço", "como cancelar compra", "como devolver produto", "como pedir reembolso"] },
  { id: "ce4e7a5b-ed73-4343-a3d1-e0da340ae447", nome: "conselhos profissionais", descricao: "Orientações para questões relacionadas aos conselhos profissionais", idCategoriaAssuntoVerde: 10064, palavrasChave: ["profissão", "oab", "cra", "crm", "crea", "cobrança indevida", "coren", "creci", "multa", "dívida", "conselho profissional", "conselho de classe", "órgão de classe", "registro profissional", "problema com conselho profissional", "problema com meu conselho", "anuidade", "mensalidade"] },
  { id: "883fae14-8892-45d8-8144-f203362ae990", nome: "consignação em pagamento", descricao: "Dificuldade para pagar: não sabe a quem pagar ou credor não quer receber", idCategoriaAssuntoVerde: 10065, palavrasChave: ["chaves", "aluguel", "dívida", "negativa", "recebimento", "receber", "pagamento", "recusa", "negatória", "ação de consignação em pagamento", "depósito judicial", "o dono do imóvel sumiu e não tenho como pagar o aluguel", "depositar o dinheiro em juízo", "o credor não quer receber", "não tenho para quem pagar", "não consigo pagar a dívida", "não sei para quem pagar"] },
  { id: "e7423346-12b5-4c02-aedf-1d3ad04df2eb", nome: "comprovar estado civil", descricao: "Documento que confirma se a pessoa é solteira, casada ou divorciada", idCategoriaAssuntoVerde: 10066, palavrasChave: ["comprovar", "solteiro", "viagem", "casamento", "venda de imóvel", "adesão", "estado civil", "certidão de solteiro", "livre para casar", "solteira", "solterice", "estado civiu"] },
  { id: "212bfd3a-6223-421e-9ef5-e60a2294316a", nome: "emancipação", descricao: "Orientações sobre emancipação de menores de idade.", idCategoriaAssuntoVerde: 10067, palavrasChave: ["capacidade civil", "menor", "maioridade", "escritura", "emancipar", "emansipação"] },
  { id: "f6131969-3afa-4600-8d1b-6acffd898596", nome: "validar rg estrangeiro", descricao: "Validar identidade de estrangeiro gratuitamente", idCategoriaAssuntoVerde: 10068, palavrasChave: ["estrangeiro", "identidade"] },
  { id: "1fdeea3a-9286-40b9-875c-1b7de80dd9ba", nome: "fgts", descricao: "Orientações sobre fgts", idCategoriaAssuntoVerde: 10069, palavrasChave: ["alvará", "saldo", "fundo de garantia", "garancia"] },
  { id: "0fe55283-4353-4cb3-8753-df073bb1f8d3", nome: "sentença de outro país", descricao: "Atendimento sobre homologação ou reconhecimento de sentença estrangeira no Brasil.", idCategoriaAssuntoVerde: 10070, palavrasChave: ["outro país", "exterior", "execução", "executoriedade", "cumprimento", "decisão", "exequatur", "divórcio estrangeiro", "adoção internacional", "sentença"] },
  { id: "c856c169-9581-42e9-b527-72dca6b1d639", nome: "mediação", descricao: "Atendimento sobre mediação de conflitos.", idCategoriaAssuntoVerde: 10073, palavrasChave: ["acordo", "extrajudicial", "conflito", "conciliação"] },
  { id: "d766f781-5bb5-4b87-b1b0-5a6600fef7e4", nome: "riocard - passe livre", descricao: "Atendimento relacionado ao riocard e passe livre", idCategoriaAssuntoVerde: 10075, palavrasChave: ["passe livre", "idoso", "estudante", "universitário", "cartão", "passagem", "gratuidade", "isenção", "deficiente físico", "ônibus", "vale-transporte", "bilhete único", "tarifa", "meio-passe", "transporte", "riocard - passe livre", "cartão do ônibus", "cartão de passagem", "cartão de transporte", "cartão de gratuidade", "cartão de ônibus", "jaé", "já é"] },
  { id: "4b8ce25b-df59-43ee-a761-eba508a81e8b", nome: "renúncia advogado", descricao: "Transferir processo para a defensoria", idCategoriaAssuntoVerde: 10076, palavrasChave: ["revogação de poderes", "patrocínio da defensoria pública", "renúncia", "destituição advogado particular", "trocar advogado", "substituir advogado", "revogar procuração", "cancelar procuração", "retirar advogado do processo", "quero trocar de advogado", "advogado do processo"] },
  { id: "fe9e8dad-8caf-4a0b-a636-2d7a1af52ace", nome: "protesto de títulos", descricao: "Atendimento para a isenção da taxa de baixa do protesto de título", idCategoriaAssuntoVerde: 10078, palavrasChave: ["taxa", "cartório", "nome sujo", "negativado", "dívida", "pagamento", "isenção", "gratuidade", "protesto", "título", "protestado", "baixar", "cancelamento de protesto", "meu nome foi protestado", "recebi protesto", "pagar protesto"] },
  { id: "c312a394-aa2b-45cc-8067-bf7a18753728", nome: "autorização para viagem", descricao: "Orientações para viagem de crianças e adolescentes", idCategoriaAssuntoVerde: 10082, palavrasChave: ["menor", "negativa", "desacompanhado", "companhia", "pais", "viajar", "autorização de viagem para menor", "autorização judicial de viagem", "levar filho para o exterior", "viagem para fora do país", "o pai não quer assinar para o filho viajar", "preciso de um papel para meu filho viajar", "autorização para menor viajar sozinho de avião", "autorisação de viagem", "papel pro menor viajar", "autorização viajem", "permissao", "meu filho vai viajar sozinho", "criança viajando sozinha", "como fazer papel de viagem para menor", "como autorizar meu filho a viajar", "o que precisa para menor viajar"] },
  { id: "1854cf60-119f-4111-94e7-a170d5ab406c", nome: "reclamação trabalhista", descricao: "Não atuamos em casos trabalhistas. procure o sindicato da sua categoria", idCategoriaAssuntoVerde: 10085, palavrasChave: ["empregado", "empregador", "trabalho", "salário", "pagamento", "carteira de trabalho", "ctps", "vínculo", "indenização", "indenizatória", "processo trabalhista", "ação trabalhista", "direito trabalhista", "quero processar a empresa", "quero processar meu patrão", "quero processar meu empregador", "trabalhei sem carteira assinada", "trabalhei sem registro", "empresa não registrou", "não pagaram rescisão", "não pagaram fgts", "não pagaram férias", "não pagaram horas extras"], mensagemFixa: "Não atuamos em casos trabalhistas — procure o sindicato da sua categoria." },
  { id: "40dcee20-425f-4e96-98fe-72c4e21a9fcf", nome: "abrir/reconhecer firma", descricao: "Orientação sobre gratuidade para abrir ou reconhecer firma em cartório", idCategoriaAssuntoVerde: 10086, palavrasChave: ["autenticação", "fichamento", "assinatura", "cartório", "gratuidade", "isenção", "reconhecimento de firma", "reconhecer assinatura", "abrir firma", "abrir ficha de assinatura", "validar firma", "autenticar assinatura", "assinatura por semelhança", "assinatura por autenticidade", "registrar assinatura", "assinar documento no cartório", "firma aberta", "reconhecer fima", "abrir fima", "autentica assinatura", "recohecimento de firma", "assinatura autenticada", "ofício", "notas", "cartório de notas", "abertura", "reconhecer firma", "reconhecer firma no cartorio", "reconhecer firma em documento", "reconhecer firma em contrato", "reconhecer minha assinatura", "reconhecimento de assinatura", "firma reconhecida", "documento com firma reconhecida", "contrato com firma reconhecida", "abrir firma no cartorio", "cadastrar assinatura", "cadastro de assinatura", "cadastrar assinatura no cartorio", "fazer firma no cartorio", "papel com firma reconhecida", "reconheser firma"] },
  { id: "94678cf8-f791-422e-a53c-81344f3cab17", nome: "certidões de nada consta", descricao: "Gratuidade para certidões: nada consta, interdição, tutela e fiscais", idCategoriaAssuntoVerde: 10087, palavrasChave: ["nada consta", "interdições e tutelas", "5º e 6ª ofícios", "1º e 2º ofícios", "execução fiscal", "carta", "vigilância", "vigilante", "1º ao 4ª", "feitos cíveis", "certidão dos distribuidores", "certidão criminal", "certidão cível", "certidão de execuções fiscais", "certidão de interdição e tutela", "certidão negativa / certidão positiva", "certidão de processos", "certidão do fórum"] },
  { id: "82ebf85d-e152-4d95-89f6-9e150f42290f", nome: "doação de bens", descricao: "Transferir propriedade de bens (carro, imóvel, etc) para outra pessoa", idCategoriaAssuntoVerde: 10088, palavrasChave: ["carro", "veículo", "casa", "apartamento", "moto", "imóvel", "móveis", "dar", "patrimônio", "adiantamento de legítima", "antecipação da herança", "passar", "nome", "bem", "bens", "doar", "passar bem", "passar casa", "passar imóvel", "passar carro"] },
  { id: "7977ffb8-1b6e-46e5-9865-a32a39f63f12", nome: "busca cartorária rgi", descricao: "Orientação sobre como localizar o cartório onde um imóvel foi registrado", idCategoriaAssuntoVerde: 10089, palavrasChave: ["imóvel", "cartório", "registro", "procurar", "terreno", "certidão", "matrícula do imóvel", "ônus reais", "inteiro teor", "averbação", "saber quem é o dono do imóvel", "ver se a casa tem dívida", "quero tirar a matrícula da minha casa", "ver se o apartamento está no nome de quem está vendendo", "puxar a ficha do imóvel", "documento para saber se a casa é legalizada", "certidão de matrícula", "consulta de matrícula", "consulta de imóvel", "consulta no rgi", "ver registro da casa", "ver documento do imóvel", "ver se o imóvel está regular"] },
  { id: "1dc59849-fbee-4a39-879a-3b3656088009", nome: "escritura do imóvel", descricao: "Orientação sobre gratuidade para escritura e certidão de ônus reais", idCategoriaAssuntoVerde: 10090, palavrasChave: ["imóvel", "proprietário", "propriedade", "terreno", "casa", "apartamento", "cartório", "registro", "escritura", "certidão de ônus reais", "escritura pública de compra e venda", "matrícula do imóvel", "averbação de escritura", "certidão negativa de ônus", "título de propriedade", "imóvel está penhorado", "hipoteca", "escritura definitiva", "documento da casa", "papel do terreno", "escritura do imóvel"] },
  { id: "9d29d196-2fc8-4514-ad1b-45f497e8402a", nome: "minha casa, minha vida", descricao: "Atendimento para questões envolvendo o programa minha casa, minha vida.", idCategoriaAssuntoVerde: 10091, palavrasChave: ["imóvel", "apartamento", "sorteio", "financiamento", "programa", "habitação", "popular", "mrv", "tenda", "cooperativa habitacional", "programa habitacional"] },
  { id: "9ceda0e8-b792-4419-934b-67ad3667d706", nome: "loas", descricao: "Para bpc/loas ou amparo social, busque a defensoria da união (dpu)", idCategoriaAssuntoVerde: 10092, palavrasChave: ["amparo social", "bpc", "deficiente", "deficiencia", "inss"], mensagemFixa: "Para BPC/LOAS ou amparo social, busque a Defensoria da União (DPU)." },
  { id: "c42fa9de-3dd8-4860-a2bf-e2add61c4b02", nome: "processo administrativo", descricao: "Atendimento para processos administrativos", idCategoriaAssuntoVerde: 10093, palavrasChave: ["procedimento", "disciplinar", "pad", "comissão", "inquérito", "servidor público", "funcionário público", "serviço público", "taxa", "imposto", "recurso", "recorrer", "prefeitura"] },
  { id: "a4d888a1-d4e4-4591-a0b6-ddc4ed229433", nome: "direitos autorais", descricao: "Defesa de direitos autorais e obras intelectuais (música, arte, livros)", idCategoriaAssuntoVerde: 10094, palavrasChave: ["obra", "música", "título", "livro", "propriedade", "autor", "autoria", "criação", "intelectual", "poesia", "texto", "escultura", "domínio público", "plágio", "ecad", "pirataria", "registrar", "altorais", "registro de marca", "proteção autoral", "usaram minha obra", "usaram meu texto", "usaram minha música", "copiaram meu trabalho", "roubaram minha ideia"] },
  { id: "f3ba839c-85ac-4c0d-bec5-bfbced453dbc", nome: "apostilar documentos", descricao: "Autenticar documentos brasileiros para serem aceitos no exterior", idCategoriaAssuntoVerde: 10101, palavrasChave: ["autenticação", "documento", "estrangeiro", "exterior", "validação", "haia", "apostila", "convenção", "apostilamento", "legalização de documentos", "validar diploma fora do brasil", "cidadania", "país", "apostila de haia", "apostilar", "documento exterior", "usar no exterior", "outro pais", "estudar fora", "trabalhar no exterior", "morar fora", "consulado", "embaixada", "diploma", "historico escolar", "certidao de nascimento", "certidao de casamento", "certidao de obito", "procuracao", "postilamento"] },
  { id: "e8841770-0398-4e1f-a2bc-eb3f68f8d242", nome: "direitos e diversidade", descricao: "Direitos e defesa para questões de diversidade de gênero e raça", idCategoriaAssuntoVerde: 10105, palavrasChave: ["cirurgia", "diversidade", "gay", "homoafetividade", "homossexual", "identidade", "lgbt", "sexo", "transexual", "transgênero", "gênero", "requalificação civil", "operação", "dano moral", "discriminação", "homofobia", "ofensa", "agressão", "intolerância", "violência", "raça", "etnia", "cor", "étnico", "racial", "sexual", "racismo", "injúria", "lgbtfobia", "nome social", "cotas raciais", "heteroidentificação", "mudar", "trans", "liberdade religiosa", "questões da diversidade de gênero", "discriminação racial", "discriminação de gênero", "preconceito", "preconceito racial", "troca de nome", "mudança de nome", "retificação de nome", "retificação de gênero", "trocar genero", "mudar de sexo", "alterar certidão", "travesti", "lgbtqia", "transfobia", "injuria racial", "intolerancia religiosa", "crimes raciais", "igualdade racial", "genero", "injuria", "retificacao", "lgbtq", "racissmo", "preconseito", "quero mudar meu nome", "\"sofri preconceito"] },
  { id: "b2aea666-4c40-46bb-a998-4a9e89716ebb", nome: "atendimento ao servidor público estadual civil", descricao: "Atendimento para servidores públicos estaduais que respondem por processos judiciais em razão do exercício da sua função.", idCategoriaAssuntoVerde: 10106, palavrasChave: [] },
  { id: "501620ac-9427-4413-ab9f-81b7fd71ac28", nome: "ação rescisória/revisão", descricao: "Revisão de processo encerrado (ação rescisória e revisão criminal)", idCategoriaAssuntoVerde: 10108, palavrasChave: ["sentença", "decisão", "recurso", "rever", "coisa julgada", "prova nova", "apareceu uma prova nova agora", "ação rescisória", "revisão criminal", "anular processo", "anular julgamento"] },
  { id: "74b9f770-c3bf-442c-8e9d-3181ae068f9e", nome: "queixa-crime", descricao: "Crimes de menor potencial: ação penal iniciada pela própria vítima", idCategoriaAssuntoVerde: 10110, palavrasChave: ["denúncia", "potencial ofensivo", "ação penal privada", "crime", "representação criminal", "ação criminal particular", "fui ofendido", "fui xingado", "me caluniaram", "me difamaram", "me injuriaram", "calunia", "injuria", "difamacao"] },
  { id: "7585190d-81ca-4b47-bb45-e50fbfd6e470", nome: "prisão em flagrante", descricao: "Atendimento sobre prisão em flagrante.", idCategoriaAssuntoVerde: 10111, palavrasChave: ["flagrante delito", "foi preso na hora do crime", "a polícia prendeu na hora", "foi pego na hora", "delegacia"] },
  { id: "387d436b-530b-41ab-8dea-46c982f40b65", nome: "defesa da criança", descricao: "Atendimento para defesa de crianças ou adolescentes", idCategoriaAssuntoVerde: 10112, palavrasChave: ["menor", "infrator", "prisão", "filho", "preso", "apreendido", "flagrante", "responsabilidade civil", "indenização", "operação", "policial", "medida de proteção", "medida protetiva", "estatuto da criança e do adolescente", "eca", "ato infracional", "medida socioeducativa", "exploração infantil"] },
  { id: "7371aee7-e6af-4bf2-96d9-6d1202c8656f", nome: "declaração de ausência", descricao: "Ação de declaração de ausência para pessoas desaparecidas", idCategoriaAssuntoVerde: 10114, palavrasChave: ["ausência", "declaração", "desaparecimento", "sumiu", "local incerto", "não sabido", "morte presumida", "sucessão provissória", "ausente", "desaparecido", "movimentar conta bancária", "dinheiro", "auzencia", "declarar ausência", "desapareceu", "não temos notícia", "cuidar dos bens", "auzensia"] },
  { id: "cba25887-86c3-4ce5-8dc0-c771a830e9cd", nome: "obter prontuário médico", descricao: "Atendimento quando a recusa do hospital em fornecer o prontuário médico", idCategoriaAssuntoVerde: 10115, palavrasChave: ["histórico", "atendimento", "saúde", "negativa", "entrega", "atestado", "laudo", "prescrição", "hospital", "clínica", "upa", "internação", "dpvat", "exames", "boletim de atendimento", "documento médico", "relatório médico"] },
  { id: "4128bcaa-b87c-4921-80ed-f4d9e9ec63df", nome: "acordo penal (anpp)", descricao: "Orientação e defesa em acordo de não persecução penal (anpp)", idCategoriaAssuntoVerde: 10116, palavrasChave: ["pip", "acordo", "inquérito", "anpp", "mp", "delegacia", "acordo com o ministério público", "proposta de acordo penal", "o promotor ofereceu um acordo", "acordo de não perseguição", "acordo da promotoria", "acordo com o mp", "anp penal", "acordo para nao ser julgado", "acordo penal", "acordo criminal"] },
  { id: "521a7357-b369-4d7e-bf29-e87a7f746486", nome: "doação de órgãos", descricao: "Atendimento para conseguir autorização para doação de órgãos e tecidos", idCategoriaAssuntoVerde: 10117, palavrasChave: ["doação de órgãos", "doar", "ser doador de órgãos", "deixar por escrito que sou doador", "documento para ser doador", "autorização da família para transplante", "retirada de órgãos", "doação de tecidos", "quero deixar autorizado doação de órgãos", "quero deixar registrado que sou doador", "quero deixar documento de doador", "quero registrar que sou doador", "doação para transplante"] },
  { id: "c22a3c73-6e57-4d69-a9c4-2b6c341aaa49", nome: "auxílios e benefícios", descricao: "Atendimento para auxílios e benefícios negados ou com valores incorretos", idCategoriaAssuntoVerde: 10118, palavrasChave: ["benefícios", "ajuda", "supera", "governo", "estado", "renda mínima", "contestação", "negativa", "recomeçar", "auxílio emergencial", "bolsa família", "auxílio brasil", "bpc", "loas", "cadúnico", "auxílio gás", "benefício bloqueado", "auxílio cancelado", "benefício suspenso", "cadastro desatualizado", "valor errado do benefício", "meu auxílio foi cortado", "ajuda para quem está desempregado", "solicitar auxílio", "benefício", "programa social", "auxílio do governo"] },
  { id: "f826ff64-6aa8-4750-b0a5-ca8d09bde9e9", nome: "cartão merenda", descricao: "Garantia do benefício de alimentação escolar da rede municipal do rio", idCategoriaAssuntoVerde: 10120, palavrasChave: ["saldo", "recarga", "benefício", "prefeitura", "cartão merenda", "escola", "cartão alimentação da escola", "merenda"] },
  { id: "915c97ae-16ff-414a-87bc-9e9ce1d84c73", nome: "prisão civil (alimentos)", descricao: "Prisão por dívida de pensão alimentícia", idCategoriaAssuntoVerde: 10121, palavrasChave: [] },
  { id: "adc3a192-cde1-4034-b3c1-867eac80819b", nome: "ação contra 123 milhas", descricao: "Direito do consumidor: cancelamento e reembolsos da 123 milhas", idCategoriaAssuntoVerde: 10123, palavrasChave: [] },
  { id: "16ef5045-8ade-42b3-9843-727cf0cdd1e1", nome: "faq", descricao: "Perguntas frequentes sobre atendimento da Defensoria Pública.", idCategoriaAssuntoVerde: 10126, palavrasChave: [] },
  { id: "26635f4e-5cb1-46fd-81b8-0e71453c385c", nome: "pessoas desaparecidas", descricao: "Orientação para auxílio na busca de pessoas desaparecidas", idCategoriaAssuntoVerde: 10130, palavrasChave: ["pessoa desaparecida", "desaparecidos", "encontrar familiar", "desaparecimento", "cadastro nacional de pessoas desaparecidas", "meu filho sumiu", "não voltou para casa", "pessoa sumida", "localizar paradeiro", "como achar alguém desaparecido", "sumiu", "procurar meu filho", "procurar minha filha", "procurar meu pai", "procurar minha mãe", "procurar familiar"] },
  { id: "79962265-f4f1-434c-8b00-7aaaa44eded9", nome: "dívida ativa", descricao: "Atendimento sobre dívida ativa com o governo ou prefeitura — IPTU, IPVA, impostos atrasados, execução fiscal.", idCategoriaAssuntoVerde: 10133, palavrasChave: ["dívida", "governo", "prefeitura", "estado", "certidão", "iptu", "ipva", "imposto", "multa", "cobrança", "parcelar", "divida com o governo", "divida com a prefeitura", "execucao fiscal", "imposto atrasado", "protesto em cartorio"] },
  { id: "72fabeb1-16f5-4d1d-85ea-9c3759781833", nome: "imigração e refúgio", descricao: "Atendimento sobre imigração, refúgio, asilo e regularização de estrangeiros no Brasil.", idCategoriaAssuntoVerde: 10134, palavrasChave: ["estrangeiro", "imigrante", "migrante", "refugiado", "apátrida", "asilo", "asilado", "regularizar", "pedir refúgio", "renovar refúgio", "renovar rnm", "protocolo de refúgio", "vim de outro país e preciso de documentos", "meu protocolo da polícia federal vai vencer", "como pedir refúgio", "quero tirar o rnm", "venezuela", "haiti", "angola", "síria", "cuba", "colômbia", "orientação", "ajuda"] },
  { id: "883fd726-6970-47d1-b3e1-4105612aa70f", nome: "autorização menor redes sociais", descricao: "Atendimento sobre autorização judicial para menor de idade trabalhar ou monetizar conteúdo em redes sociais (influencer mirim).", idCategoriaAssuntoVerde: 10135, palavrasChave: ["alvará judicial", "postagens pagas", "contéudo", "publicidade", "conta monetizada", "instagram", "trabalho", "remuneração", "infantil", "filho", "monetizar", "menor", "alvará", "trabalhar", "publi", "criança", "mirim", "eca digital", "influencer", "youtube", "tiktok", "canal"] },
];

// Mesmas checagens que antes viviam em fluxos/catalogo.test.ts — faz
// sentido rodar 1x aqui (dado estático, migrado 1x) em vez de manter como
// suíte de teste perpétua sobre uma tabela que passa a ser editada por SQL.
function validar(dados: FluxoPlanejado[]): void {
  const idsImplementados = new Set(
    Object.values(fluxosPorId)
      .map((f) => f.idCategoriaAssuntoVerde)
      .filter((id): id is number => id !== undefined)
  );
  const idsVistos = new Set<string>();
  const categoriasVistas = new Set<number>();
  for (const f of dados) {
    if (idsImplementados.has(f.idCategoriaAssuntoVerde)) {
      throw new Error(`${f.nome} (idCategoriaAssuntoVerde ${f.idCategoriaAssuntoVerde}) duplica um fluxo já implementado`);
    }
    if (categoriasVistas.has(f.idCategoriaAssuntoVerde)) {
      throw new Error(`idCategoriaAssuntoVerde ${f.idCategoriaAssuntoVerde} repetido dentro do próprio seed (${f.nome})`);
    }
    categoriasVistas.add(f.idCategoriaAssuntoVerde);
    if (f.descricao.trim().length === 0) throw new Error(`${f.nome} está com descricao vazia`);
    if (idsVistos.has(f.id)) throw new Error(`uuid ${f.id} repetido dentro do seed (${f.nome})`);
    if (f.id in fluxosPorId) throw new Error(`${f.id} colide com um fluxo já implementado`);
    idsVistos.add(f.id);
    if (!Array.isArray(f.palavrasChave)) throw new Error(`${f.nome} deveria ter palavrasChave como array`);
  }
  if (dados.length !== 74) throw new Error(`esperava 74 registros no seed, achou ${dados.length} — dado mudou? confirmar antes de seguir`);
}

async function seed(): Promise<void> {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL obrigatório pra rodar o seed");

  validar(DADOS_SEED);

  const pool = new Pool({ connectionString: url });
  await pool.query(`
    CREATE TABLE IF NOT EXISTS fluxos_planejados (
      id TEXT PRIMARY KEY,
      nome TEXT NOT NULL,
      descricao TEXT NOT NULL,
      id_categoria_assunto_verde INTEGER NOT NULL,
      palavras_chave TEXT[] NOT NULL DEFAULT '{}'
    )
  `);
  // Issue #22 — coluna nova numa tabela que já existe (issue #26).
  await pool.query(`ALTER TABLE fluxos_planejados ADD COLUMN IF NOT EXISTS mensagem_fixa TEXT`);

  for (const f of DADOS_SEED) {
    await pool.query(
      `INSERT INTO fluxos_planejados (id, nome, descricao, id_categoria_assunto_verde, palavras_chave, mensagem_fixa)
       VALUES ($1, $2, $3, $4, $5, $6)
       ON CONFLICT (id) DO UPDATE SET nome = $2, descricao = $3, id_categoria_assunto_verde = $4, palavras_chave = $5, mensagem_fixa = $6`,
      [f.id, f.nome, f.descricao, f.idCategoriaAssuntoVerde, f.palavrasChave, f.mensagemFixa ?? null]
    );
  }

  console.log(`seed concluído: ${DADOS_SEED.length} fluxos planejados inseridos/atualizados em fluxos_planejados`);
  await pool.end();
}

seed().catch((erro) => {
  console.error("seed falhou:", erro);
  process.exit(1);
});
